'use client';

export interface OfflineLead {
  id: string;
  timestamp: number;
  contactFields: {
    name: string | null;
    company: string | null;
    title: string | null;
    email: string | null;
    phone: string | null;
  };
  audioBase64?: string | null;
  audioMimeType?: string | null;
  cardImageBase64?: string | null;
  campaignId?: string | null;
  exhibition?: string | null;
  exhibition_id?: string | null;
  stall?: string | null;
}

export class OfflineStorage {
  private static STORAGE_KEY = 'exhibition_crm_offline_leads';

  public static getQueue(): OfflineLead[] {
    if (typeof window === 'undefined') return [];
    try {
      const stored = localStorage.getItem(this.STORAGE_KEY);
      return stored ? JSON.parse(stored) : [];
    } catch (e) {
      console.error('Failed to read offline queue:', e);
      return [];
    }
  }

  public static saveQueue(queue: OfflineLead[]) {
    if (typeof window === 'undefined') return;
    try {
      localStorage.setItem(this.STORAGE_KEY, JSON.stringify(queue));
    } catch (e) {
      console.error('Failed to save offline queue:', e);
    }
  }

  public static enqueue(lead: Omit<OfflineLead, 'id' | 'timestamp'>): OfflineLead {
    const queue = this.getQueue();
    const newLead: OfflineLead = {
      ...lead,
      id: `offline_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
      timestamp: Date.now(),
    };
    queue.push(newLead);
    this.saveQueue(queue);
    
    // Dispatch custom event to notify other components of update
    if (typeof window !== 'undefined') {
      window.dispatchEvent(new Event('offline-queue-updated'));
    }
    
    return newLead;
  }

  public static dequeue(id: string) {
    let queue = this.getQueue();
    queue = queue.filter(item => item.id !== id);
    this.saveQueue(queue);
    
    if (typeof window !== 'undefined') {
      window.dispatchEvent(new Event('offline-queue-updated'));
    }
  }

  public static clear() {
    if (typeof window === 'undefined') return;
    localStorage.removeItem(this.STORAGE_KEY);
    
    if (typeof window !== 'undefined') {
      window.dispatchEvent(new Event('offline-queue-updated'));
    }
  }
}

/**
 * Synchronizes a locally cached offline lead to the Supabase Cloud DB and triggers AI processing.
 */
export async function syncOfflineLead(offlineLead: OfflineLead): Promise<boolean> {
  try {
    const mockOrgId = '738de77c-ddd0-4a71-9d8d-3e346590ca0d'; // Mock organization ID
    
    // 1. Initialize lead in 'capturing' state in cloud DB
    const startRes = await fetch('/api/leads/recording/start', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ 
        organizationId: mockOrgId, 
        userId: null,
        campaignId: offlineLead.campaignId || null
      }),
    });
    
    if (!startRes.ok) throw new Error('Cloud DB initialization failed.');
    const startResult = await startRes.json();
    const leadId = startResult.data?.leadId;

    if (!leadId) throw new Error('Lead ID not generated by start route.');

    // 2. Upload recording (if exists) to run transcription/context extraction
    if (offlineLead.audioBase64 && offlineLead.audioMimeType) {
      // Decode base64 to Blob
      const response = await fetch(offlineLead.audioBase64);
      const audioBlob = await response.blob();
      
      const formData = new FormData();
      formData.append('audio', audioBlob);
      formData.append('leadId', leadId);
      formData.append('organizationId', mockOrgId);

      const stopRes = await fetch('/api/leads/recording/stop', {
        method: 'POST',
        body: formData,
      });

      if (!stopRes.ok) throw new Error('Offline voice processing failed.');
    }

    // 3. Save confirmed contact fields and scanned card image
    const saveRes = await fetch(`/api/leads/${leadId}/save`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        contactFields: offlineLead.contactFields,
        cardImage: offlineLead.cardImageBase64 || null,
        confidence: offlineLead.cardImageBase64 ? 0.95 : 1.0,
        campaignId: offlineLead.campaignId || null
      }),
    });

    if (!saveRes.ok) throw new Error('Offline contact save failed.');

    return true;
  } catch (error) {
    console.error(`Sync error for offline lead ${offlineLead.id}:`, error);
    return false;
  }
}
